// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Proximity.Gui.GtkSharp {
    
    
    public partial class GtkExceptionWindow {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Proximity.Gui.GtkSharp.GtkExceptionWindow
            this.Name = "Proximity.Gui.GtkSharp.GtkExceptionWindow";
            this.Title = Mono.Unix.Catalog.GetString("GtkExceptionWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
